Changing config files.

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -1,5 +1,9 @@
 name: "Step 2: Publish Release"
 on:
+  workflow_run:
+    workflows: ["Step 1: Prep Release"]
+    types:
+      - completed
   workflow_dispatch:
     inputs:
       branch:
@@ -16,16 +20,34 @@ jobs:
   publish_release:
     runs-on: ubuntu-latest
     environment: release
-    permissions:
-      id-token: write
     steps:
+      - name: Debug APP_ID
+        run: |
+          echo "APP_ID: ${{ vars.APP_ID }}"
+      - name: Debug APP_PRIVATE_KEY
+        run: |
+          echo "APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}"
+      
       - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
 
-      - uses: actions/create-github-app-token@v1
+      - uses: actions/create-github-app-token@v2
         id: app-token
         with:
           app-id: ${{ vars.APP_ID }}
           private-key: ${{ secrets.APP_PRIVATE_KEY }}
+      
+      - name: Check Token Generation
+        run: |
+          if [ -z "${{ steps.app-token.outputs.token }}" ]; then
+            echo "Error: Token generation failed."
+            exit 1
+          else
+            echo "Token generated successfully."
+          fi
+      
+      # - name: Check release URL
+      #   run: |
+      #     echo "Release URL: ${{ github.event.inputs.release_url }}"
 
       - name: Populate Release
         id: populate-release
@@ -34,16 +56,18 @@ jobs:
           token: ${{ steps.app-token.outputs.token }}
           branch: ${{ github.event.inputs.branch }}
           release_url: ${{ github.event.inputs.release_url }}
-          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}
+          steps_to_skip: "check-npm,publish-npm,publish-assets"
 
       - name: Finalize Release
         id: finalize-release
         env:
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
         uses: jupyter-server/jupyter_releaser/.github/actions/finalize-release@v2
         with:
           token: ${{ steps.app-token.outputs.token }}
           release_url: ${{ steps.populate-release.outputs.release_url }}
+          steps_to_skip: "publish-npm,publish-assets"
 
       - name: "** Next Step **"
         if: ${{ success() }}
@@ -56,3 +80,5 @@ jobs:
         run: |
           echo "Failed to Publish the Draft Release Url:"
           echo ${{ steps.populate-release.outputs.release_url }}
+permissions:
+  contents: write
